### ISSUE TITLE
Foreseen usage

### ISSUE THREAD

**Issue by baerbock** [mapbox/Hecate#162]
Hi Nick,

should Hecate be used from JOSM as OSM API replacement? Or with proprietary Mapbox tools nobody (yet) knows?

cc/ @ingalls

**Comment by ingalls** [comment]
Hey @baerbock,

> should Hecate be used from JOSM as OSM API replacement

We're a generation ahead in some ways between a traditional Geo/MapServer and the OSM API. The OSM data format makes automated edits very difficult to manage due to the shared node/way concept as well as the lack of atomic changesets. Mapservers on the other end of the spectrum typically don't support the version history and multi-user flexibility that the OSM API has.

Hecate isn't a drop in replacement for the OSM API. Although it supports all Hecate Data => JOSM, due to the shared node/way concept above, JOSM can currently only be used to edit point data.

We use Hecate internally for large portions of the data that powers our geocoding API. Much of this data is modified in an automated fashion using the library/cli tools found in https://github.com/mapbox/HecateJS

> Or with proprietary Mapbox tools nobody (yet) knows?

No secret sauce here! All the building blocks and scripts are Open Source between the Hecate and HecateJS repos. I'm hoping to do a big documentation sprint on HecateJS in the coming month or two.
