### ISSUE TITLE
Add "upsert" option for keys

### ISSUE THREAD

**Issue by mattficke** [mapbox/Hecate#77]
A new `key` value was added in https://github.com/mapbox/Hecate/pull/70, which helps us avoid creating duplicate features in the database. The current behavior is to return an error when attempting to insert a feature with a pre-existing `key`. It would be helpful if there was also an "upsert" option, so that the conflicting feature is updated with the new value instead.

Postgres includes this feature: https://www.postgresql.org/docs/9.6/static/sql-insert.html

cc @ingalls @lukasmartinelli @yhahn

**Comment by ingalls** [comment]
Unfortunately a pure UPSERT operation isn't possible due to the transactional, non-locking nature of deltas.

A conflicting `key` can be quickly found and an error thrown but an upsert operation without the client knowing the `version` of the given feature on the server would result in the ability for multiple clients to push conflicting changes simultaneously.

---

That said, a two pronged approach can simplify the `UPSERT` style operation. The first is a new search by key query endpoint, which will return the feature for a given key query. Ref: https://github.com/mapbox/Hecate/pull/78

The second is to have a more standard JSON response for upload errors that where possible returns the feature that caused the error. This change is pending.

**Comment by ingalls** [comment]
Error by id has landed here: https://github.com/mapbox/Hecate/pull/80
